### ISSUE TITLE
A small typo

### ISSUE THREAD

**Issue by fuzihaofzh** [tengyuma/cs229m_notes#28]
Hi, all,
Thanks for sharing this great course and notes. Just a small typo:

page 92: "We visualize the these functions" -> "We visualize these functions"
Page 112:  "but the the initialization scale" -> "but the initialization scale"

Best,
Zihao

**Comment by tengyuma** [comment]
Fixed; Thanks Zihao! 

More corrections are more than welcome!

**Comment by tengyuma** [comment]
as above
